plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
